Androidから再生する際にVLCを起動する
Chinachu/Chinachu pull request #303
Opened 2017-01-06 15:45 UTC by tmyt

AndroidのChromeからアクセスすると、MobileSafari扱いになりvlc-x-callbackスキームで開こうとします。
しかし、Android版のVLCはvlc-x-callbackスキームをサポートしていないため、代わりにintentスキームを使用して開くように変更しました。

これによりAndroidでアクセスした場合、VLCがインストールされていればVLCで。されていなければPlayストアのVLCの画面が表示されるようになります。

2017-01-11 06:21 UTC, shirow-github commented
ライブ視聴を有効にする場合、web/page/channel/watch.jsもweb/page/program/watch.js同様の
修正が必要なようです。

2017-01-11 10:26 UTC, tmyt commented
ライブ視聴の場合の修正が抜けていたので追加しました。再生ボタンを押したときの動作は、録画済みを再生する場合と同様です。

2017-01-14 01:08 UTC, kanreisa requested changes

2017-01-14 01:08 UTC, kanreisa commented on web/lib/prototype.js
> +      Android:        ua.indexOf('Linux; Android') > -1
これはアカん

2017-01-14 01:08 UTC, kanreisa commented on web/lib/prototype.js
> +      Android:        ua.indexOf('Linux; Android') > -1
@tmyt このツッコミ届いてますか。ライブラリは書き換えちゃだめです。

2017-01-14 01:10 UTC, tmyt commented on web/lib/prototype.js
> +      Android:        ua.indexOf('Linux; Android') > -1
そこライブラリだったの…ちょっと出直してきます…

2017-01-16 04:27 UTC, tmyt commented
ライブラリの変更Revertして、毎回UserAgent見るようにしてみました…

2017-01-16 05:40 UTC, kanreisa commented on web/page/channel/watch.js
> +						if (navigator.userAgent.indexOf('Android') >= 0) {
ここ非常に可読性が悪いので、
`navigator.userAgent.indexOf('Android') !== -1` だったらマージしたんですが、
とりあえず修正するなら
`/Android/.test(navigator.userAgent) === true`
こっちがオススメ。

2017-01-16 06:11 UTC, mzyy94 commented on web/page/channel/watch.js
> +						if (navigator.userAgent.indexOf('Android') >= 0) {
node-6.9以上を対象にしている現状ですし、
`if (navigator.userAgent.includes('Android'))` といった在り方も

2017-01-16 06:12 UTC, kanreisa commented on web/page/channel/watch.js
> +						if (navigator.userAgent.indexOf('Android') >= 0) {
節子、そこnodeやない。

2017-01-16 06:12 UTC, mzyy94 commented on web/page/channel/watch.js
> +						if (navigator.userAgent.indexOf('Android') >= 0) {
せやった

2017-01-16 10:21 UTC, tmyt commented on web/page/channel/watch.js
> +						if (navigator.userAgent.indexOf('Android') >= 0) {
おすすめなほうにしました

2017-01-16 10:23 UTC, kanreisa approved these changes

2017-01-16 10:24 UTC, merged

2017-01-16 11:48 UTC, kanreisa commented
ご対応いただきありがとうございました 😇